server:
  #服务端口
  port: 80
  #路径
  servlet:
    context-path: /chen
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/infpubgrid?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
mybatis:
  type-aliases-package: com.chen.pro.entity
  config-locations: classpath:mybatis/mybatis-config.xml
  mapper-locations:
    - classpath:mybatis/mapper/*.xml
logging:
  config: classpath:log4j2-dev.xml
  level: info
marketType:
  map:
    10: 发电企业
    20: 电力用户
    30: 售电公司
    40: 电网企业
    50: 分布式发电企业
    60: 储能企业
    70: 虚拟电厂
    99: 其他